[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache = true
cache_path = 'cache'
solc = '0.8.25'

# 优化器配置
optimizer = true
optimizer_runs = 200

# 重映射
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src/'
]