[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache = true
cache_path = 'cache'
solc = "0.8.25"

# 启用 viaIR 来解决 stack too deep 问题
via_ir = true

# 使用优化器
optimizer = true
optimizer_runs = 200

# 测试配置
[fuzz]
runs = 256
max_test_rejects = 65536