spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update  # 使用update，只更新表结构不删除数据
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8081

web3j:
  enabled: true
  offline: false
  # 使用多个备选RPC节点，第一个失败会自动尝试下一个
  rpc-url: https://1rpc.io/sepolia

logging:
  level:
    com.erc20.indexer: DEBUG
    org.web3j: DEBUG
    org.hibernate.SQL: OFF
    root: INFO  # 临时设置为 ERROR 来验证
indexer:
  contract-address: "0x5F97a3a99B590D93fF798b7dCE5E917d4eEd8778"
  poll-interval: 30000    # 轮询间隔30秒
  time-window: 120000     # 时间窗口2分钟